// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging_service.proto

// Protobuf Java Version: 4.26.0
package igl3;

public interface GetMessagesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.GetMessagesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
