// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging_service.proto

// Protobuf Java Version: 4.26.0
package igl3;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string sender = 2;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 2;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string recipient = 3;</code>
   * @return The recipient.
   */
  java.lang.String getRecipient();
  /**
   * <code>string recipient = 3;</code>
   * @return The bytes for recipient.
   */
  com.google.protobuf.ByteString
      getRecipientBytes();

  /**
   * <code>string text = 4;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 4;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
